-- ============================================================
-- 021: CEREUS Creative Workflow Enhancements
-- Adds trend context, color story, design briefs, and AI tracking
-- ============================================================

-- Collections: store pinned trends and structured color story
ALTER TABLE cereus_collections
  ADD COLUMN IF NOT EXISTS trend_context JSONB DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS color_story JSONB DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS suggested_garment_types JSONB DEFAULT NULL;

COMMENT ON COLUMN cereus_collections.trend_context IS 'Pinned trends from Step 1 (silhouettes, fabrics, details, keywords)';
COMMENT ON COLUMN cereus_collections.color_story IS 'Structured color array [{hex, name, role}]';
COMMENT ON COLUMN cereus_collections.suggested_garment_types IS 'AI-suggested garment types [{category, count, notes}]';

-- Garments: store editable design brief
ALTER TABLE cereus_garments
  ADD COLUMN IF NOT EXISTS design_brief JSONB DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS brief_approved BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS sketch_source TEXT DEFAULT NULL;

COMMENT ON COLUMN cereus_garments.design_brief IS 'AI-generated + user-edited design brief JSON';
COMMENT ON COLUMN cereus_garments.brief_approved IS 'Whether designer approved the brief before visual generation';
COMMENT ON COLUMN cereus_garments.sketch_source IS 'How visual was created: dall-e, svg, manual';

-- Materials: track AI-generated fabrics
ALTER TABLE cereus_materials
  ADD COLUMN IF NOT EXISTS ai_generated BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS generation_prompt TEXT DEFAULT NULL;

COMMENT ON COLUMN cereus_materials.ai_generated IS 'Whether this material was generated by AI';
COMMENT ON COLUMN cereus_materials.generation_prompt IS 'The prompt used to generate this material (for reproducibility)';
